
version: '3.7'

services:
  db:
    image: 'jasonafs/postgres'
    ports:
      - "5432:5432"
    restart: unless-stopped
    
  adminer:
    image: 'jasonafs/adminer'
    ports:
      - "8080:80"
    depends_on:
      - db


  composer:
    image: 'jasonafs/composer-custom'



  symfony:
    image: "jasonafs/symfony"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "pgsql://my_username:pass@db/db"




